# Generated by Django 4.2.13 on 2024-06-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('horror', 'HORROR'), ('drama', 'DRAMA'), ('action', 'ACTION'), ('comedy', 'COMEDY'), ('sci-fi', 'SCI-FI'), ('western', 'WESTERN'), ('thriller', 'THRILLER'), ('documentary', 'DOCUMENTARY'), ('fantasy', 'FANTASY'), ('romance', 'ROMANCE')], default='horror', max_length=15),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
