# Generated by Django 4.2.13 on 2024-06-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_movie_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
