# Generated by Django 4.2.13 on 2024-06-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_alter_movie_genre_delete_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=2024, max_length=4, verbose_name='year'),
        ),
    ]
