# Generated by Django 4.2.13 on 2024-06-29 21:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_remove_movie_excerpt_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, editable=False, max_length=200, unique=True),
        ),
    ]
