# Generated by Django 4.2.13 on 2024-06-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_movie_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=2024, verbose_name='year'),
        ),
    ]
