# Generated by Django 4.2.13 on 2024-06-15 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_alter_movie_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-added_on']},
        ),
    ]
