# Generated by Django 4.2.13 on 2024-06-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0005_alter_movie_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.TextField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('horror', 'HORROR'), ('drama', 'DRAMA'), ('action', 'ACTION'), ('comedy', 'COMEDY'), ('sci-fi', 'SCI-FI'), ('western', 'WESTERN'), ('thriller', 'THRILLER'), ('documentary', 'DOCUMENTARY'), ('fantasy', 'FANTASY'), ('romance', 'ROMANCE'), ('crime', 'CRIME')], default='horror', max_length=15),
        ),
    ]
