# Generated by Django 4.2.13 on 2024-06-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0006_alter_movie_director_alter_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.TextField(max_length=30, unique=True),
        ),
    ]
